image:
  repository: docker.io/waydar2024/swp
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8089

serviceAccount:
  create: true  
  name: "swp-service-account"

autoscaling:
  enabled: false  # Otomatik ölçeklendirmeyi aktif etmek için true yapabilirsiniz
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: false  # Ingress kullanmak istiyorsanız true yapabilirsiniz
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}
