apiVersion: apps/v1
kind: Deployment
metadata:
  name: swp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swp
  template:
    metadata:
      labels:
        app: swp
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: swp-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
